### ISSUE TITLE
Format for sharing solutions

### ISSUE THREAD

**Issue by sureshmangs** [CodingChallegesFYI/SharedSolutions#45]
Shared solutions should also have the "language" used for conveniently finding a solution in a given language.

Sharing a table-like format:

## Build your own wc Tool
The Challenge: [Write your own wc Tool](https://codingchallenges.fyi/challenges/challenge-wc)

The shared solutions:

| No.| Solution | Language | Author |
|---|---|---|---|
| 1 | [Build your own wc Tool](https://github.com/jainmohit2001/coding-challenges/blob/master/src/1) | TypeScript | [jainmohit2001](https://github.com/jainmohit2001) |
| 2 | [Build your own wc Tool](https://github.com/Ghurtchu/wc) | Scala | [Ghurtchu](https://github.com/Ghurtchu) |
| 3 | [Build your own wc Tool](https://github.com/andrenbrandao/wc-tool) | Go | [andrenbrandao](https://github.com/andrenbrandao) |

**Comment by JohnCrickett** [comment]
Good call. It's probably times to split it up into a page per challenges with solutions grouped by language.

**Comment by JohnCrickett** [comment]
Done
