### ISSUE TITLE
Add "Scroll to Top" button in Readme.md

### ISSUE THREAD

**Issue by Pooja11kumari** [CodingChallegesFYI/SharedSolutions#50]
**Description**
Add the "Scroll to top" button in the Readme.md file.Which will act as a automatic scroller when clicked.And scrolls to the TOP of the File in just one click.

**Comment by Pooja11kumari** [comment]
@JohnCrickett I would like to work on it,can you assign this to me

**Comment by JohnCrickett** [comment]
Good call. Thanks.

**Comment by JohnCrickett** [comment]
Thanks! :)
