### ISSUE TITLE
Add a link to the Discord Server

### ISSUE THREAD

**Issue by JohnCrickett** [CodingChallegesFYI/SharedSolutions#55]
It would be great to include a link to the Discord server so people can discuss solutions: https://discord.gg/zv4RKDcEKV

**Comment by Tashuuuu** [comment]
In the README.md file?

**Comment by JohnCrickett** [comment]
Yes, it would be great to include it after the line:

Publicly shared solutions to the [Coding Challenges](https://codingchallenges.fyi/).

**Comment by Tashuuuu** [comment]
I can already see the Discord Server link there

<img width="119" alt="image" src="https://github.com/CodingChallegesFYI/SharedSolutions/assets/85075827/375b2804-a438-4eae-a650-71ed92ff229e">

**Comment by JohnCrickett** [comment]
On the website yes, not in the README here.

**Comment by JohnCrickett** [comment]
Resolved by https://github.com/CodingChallegesFYI/SharedSolutions/pull/60
