### ISSUE TITLE
Split solutions onto separate pages and create ToC on first page.

### ISSUE THREAD

**Issue by JohnCrickett** [CodingChallegesFYI/SharedSolutions#61]
The list is getting quite long. It would be great to split the solutions up with a page for each challenge.

Each page can then be moved to the format suggested in https://github.com/CodingChallegesFYI/SharedSolutions/issues/45 with a header that includes a link to the main site, the discord and the challenge the solutions relate to.

The main README.md can then become a Table of Contents.

**Comment by aaron-lee-hebert** [comment]
@JohnCrickett I'm interested in taking on this issue. Do you prefer having #45 completed separately to having the solutions moved to their own pages, or are you comfortable with having it combined into one pull request?

**Comment by JohnCrickett** [comment]
I'm happy for anyone who is kind enough to help to work in whatever way best suits them! :)

**Comment by sumanth-lingappa** [comment]
Can we also have the solutions categorised based on the programming language?

**Comment by JohnCrickett** [comment]
> Can we also have the solutions categorised based on the programming language?

I think that would be good, a table like https://github.com/CodingChallegesFYI/SharedSolutions/issues/45 grouped by language.

**Comment by JohnCrickett** [comment]
@aaron-lee-hebert thanks for the awesome work on this! Really appreciate it!

**Comment by dotslashbit** [comment]
Is this still an issue? If not, then please close this, thanks
